// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pkoblhmohzgqzbvvtszd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBrb2JsaG1vaHpncXpidnZ0c3pkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MDgxMjQsImV4cCI6MjA3MzA4NDEyNH0.rMlzSBc061QT7T5eQaMtwaFENDFW0dAmo2tcpx4e4yM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});